### ISSUE TITLE
set id3 tags via go (instead ruby)

### ISSUE THREAD

**Issue by mro** [mro/internet-radio-recorder#30]

**Comment by mro** [comment]
silent mp3s http://www.xamuel.com/blank-mp3s/

**Comment by mro** [comment]
see https://github.com/mikkyang/id3-go/issues/11#issuecomment-158690130

**Comment by mro** [comment]
https://github.com/hasty/id3

**Comment by mro** [comment]
https://github.com/search?l=Go&q=id3&type=Repositories

**Comment by mro** [comment]
a new kid in town: https://github.com/bogem/id3v2

**Comment by mro** [comment]
waiting for https://github.com/bogem/id3v2/issues/2

**Comment by mro** [comment]
http://joelverhagen.com/blog/2010/12/how-itunes-uses-id3-tags/

**Comment by mro** [comment]
@bogem thanks a lot, your lib is awesome and got me rid of both taglib and ruby!

**Comment by bogem** [comment]
You're welcome!
P.S. Today will be new version. Will be added parse capabilities!

**Comment by mro** [comment]
oh. I liked to extremely focussed, minimal, write-only idea a lot.

**Comment by bogem** [comment]
I'm too. But I think there should be one good id3 both parsing and writing library in Go. You shouldn't worry, I will support minimality of library as far as I can. And the performance of lib is as fast as it was only writing.
